# this is the docker-compose version
version: '3'

# file version 2020-06-23-1200

services:
    <IMAGE_NAME>_service:
        # use existing default network
        network_mode: bridge
        # restart this container if it crashes
        restart: always
        build:
            # build from directory in context and Dockerfile
            context: .
            dockerfile: Dockerfile
        container_name: <IMAGE_NAME>_cont_<ENVIRON>
        # update :latest to desired version
        image: <IMAGETXT>:<DESIREDTAG>
        volumes:
            # outside access for data files outside:inside
            - <INDEXPATH>:/DAPI/INDEXES:ro
            - <CONFIGPATH>:/DAPI/CONFIG:ro
            - <OUTSIDE_GDC_DATA_PATH>:/DAPI/DATA/GDC:ro
            - <LOGPATH>:/opt/tomcat/logs
            # read-only file to set time and timezone to same in image as on server
            - /etc/localtime:/etc/localtime:ro
            - /etc/localtime:/etc/timezone:ro
        ports:
            # (outside)host port:container port(inside) for Tomcat
            # outside/host port is only set here (other docker compose have ports in more than one place)
            - "<OUTSIDE_PORT>:8080"
        tty: true

