# this is the docker-compose version
version: '3'

# file version 2021-08-13-11001

networks:
    # network for this compose stack
    mob_network_hub:
        driver: bridge
#SUBNET        ipam:
#SUBNET            config:
#SUBNET            - subnet: 0
services:
    mob_service:
        networks:
            - mob_network_hub
        # restart this container if it crashes
        restart: always
        build:
            # build from directory in context and Dockerfile
            context: .
            dockerfile: Dockerfile
        container_name: mob_cont_hub
        image: mdabcb/mob_image:2021-08-13-1100
        volumes:
            # outside access for data files outside:inside
            - /MOB/indexes:/DAPI/INDEXES:ro
            - /MOB/dsc_indexes:/DAPI/DSC_INDEXES:ro
            - /MOB/config:/DAPI/CONFIG:ro
            - /MOB/DATA:/DAPI/DATA:ro
            - /MOB/logs:/opt/tomcat/logs
            # read-only file to set time to same in image as on server
            - /etc/localtime:/etc/localtime:ro
        ports:
            # (outside)host port:container port(inside) for Tomcat
            # outside/host port is only set here (other docker compose have ports in more than one place)
            - "8080:8080"
        tty: true

