# this is the docker compose version
version: '3'

# file version 2024-05-29-10001

networks:
    # network for this compose stack
    mqa_network_hub:
        driver: bridge
services:
    mqa_service:
        networks:
            - mqa_network_hub
        # restart this container if it crashes
        restart: always
        build:
            # build from directory in context and Dockerfile
            context: .
            dockerfile: Dockerfile
        container_name: mqa_cont_hub
        image: mdabcb/mqa_image:2024-05-29-1000
        volumes:
            # outside access for data files outside:inside
            - /MQA/DATA/INDEXES:/BEA/DAPI_MQA/INDEXES:ro
            - /MQA/DATA/CONFIG:/BEA/DAPI_MQA/CONFIG:ro
            - /MQA/DATA/DATA:/BEA/DAPI_MQA/DATA:ro
            - /MQA/logs:/opt/tomcat/logs
            # read-only file to set time to same in image as on server
            - /etc/localtime:/etc/localtime:ro
        ports:
            # (outside)host port:container port(inside) for Tomcat
            # outside/host port is only set here (other docker compose have ports in more than one place)
            - "8080:8080"
        tty: true

